def print_text(text):
    print(text)


if __name__ == "__main__":
    print_text("Hello World")
    print_text("Hello Python")
    print_text("Hello C++")
    print_text("Hello Java")
    print_text("Hello JavaScript")
    print_text("Hello Swift")
    print_text("Hello C#")
    print_text("Hello C")
    print_text("Hello Go")
    print_text("Hello Ruby")
    print_text("Hello Perl")
    print_text("Hello PHP")
    print_text("Hello Kotlin")
    print_text("Hello Scala")
    print_text("Hello Haskell")
    print_text("Hello Lua")
    print_text("Hello Rust")
    print_text("Hello Swift")
    print_text("Hello C#")
    print_text("Hello C")
    print_text("Hello Go")
    print_text("Hello Ruby")
    print_text("Hello Perl")
    print_text("Hello PHP")
    print_text("Hello Kotlin")
    print_text("Hello Scala")